config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :houses
  resources :performed_maintenances
  resources :performed_maintenance_parts
  resources :parts
  resources :services
  resources :maintenances
  resources :maintenance_schedules
  post 'maintenance_schedules/import' => 'maintenance_schedules#import', as: :import_maintenance_schedule
  resources :canonical_vehicles
  resources :steps
  resources :fillups
  resources :vehicles
  get 'vehicles/:id/image' => 'vehicles#image', as: :vehicle_image
  post 'vehicles/:id/fillup' => 'vehicles#fillup', as: :vehicle_fillup
  post 'vehicles/:id/import' => 'vehicles#import', as: :import_vehicle_fillups
  resources :aliases
  resources :transactions
  resources :vendors
  resources :accounts
  post 'accounts/:id/import' => 'accounts#import', as: :import_account_transactions
  resources :checking_accounts, controller: 'accounts', type: 'CheckingAccount'
  resources :stock_accounts, controller: 'accounts', type: 'StockAccount'
  get 'welcome/index'

  devise_for :users
  resources :users, :only => [:show]

  root 'welcome#index'

end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  before_action :set_alias, only: [:show, :edit, :update, :destroy]

  # GET /aliases
  # GET /aliases.json
  def index
    @aliases = Alias.all
  end

  # GET /aliases/1
  # GET /aliases/1.json
  def show
  end

  # GET /aliases/new
  def new
    @alias = Alias.new
  end

  # GET /aliases/1/edit
  def edit
  end

  # POST /aliases
  # POST /aliases.json
  def create
    @alias = Alias.new(alias_params)

    respond_to do |format|
      if @alias.save
        format.html { redirect_to @alias, notice: 'Alias was successfully created.' }
        format.json { render :show, status: :created, location: @alias }
      else
        format.html { render :new }
        format.json { render json: @alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliases/1
  # PATCH/PUT /aliases/1.json
  def update
    respond_to do |format|
      if @alias.update(alias_params)
	if(@alias.vendor_id)
	  Transaction.where(payee: @alias.payee, memo: @alias.memo).find_each do |transaction|
	    transaction.vendor_id = @alias.vendor_id
	    transaction.save
	  end
	end
        format.html { redirect_to @alias, notice: 'Alias was successfully updated.' }
        format.json { render :show, status: :ok, location: @alias }
      else
        format.html { render :edit }
        format.json { render json: @alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliases/1
  # DELETE /aliases/1.json
  def destroy
    @alias.destroy
    respond_to do |format|
      format.html { redirect_to aliases_url, notice: 'Alias was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alias
      @alias = Alias.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alias_params
      params.require(:alias).permit(:payee, :memo, :vendor_id)
    end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/views/aliases/_form.html.erb
<%= form_for(@alias) do |f| %>
  <% if @alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alias.errors.count, "error") %> prohibited this alias from being saved:</h2>

      <ul>
      <% @alias.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payee %><br>
    <%= f.text_field :payee %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_field :memo %>
  </div>
  <div class="field">
    <%= f.select :vendor_id, options_for_select(Vendor.order(:name).map{|s|[s.name, s.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aliases/edit.html.erb
<h1>Editing Alias</h1>

<%= render 'form' %>

<%= link_to 'Show', @alias %> |
<%= link_to 'Back', aliases_path %>

app/views/aliases/index.html.erb
<h1>Listing Aliases</h1>

<table>
  <thead>
    <tr>
      <th>Payee</th>
      <th>Memo</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aliases.each do |alias| %>
      <tr>
        <td><%= alias.payee %></td>
        <td><%= alias.memo %></td>
        <td><%= alias.vendor %></td>
        <td><%= link_to 'Show', alias %></td>
        <td><%= link_to 'Edit', edit_alias_path(alias) %></td>
        <td><%= link_to 'Destroy', alias, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alias', new_alias_path %>

app/views/aliases/new.html.erb
<h1>New Alias</h1>

<%= render 'form' %>

<%= link_to 'Back', aliases_path %>

app/views/aliases/show.html.erb
<p>
  <strong>Payee:</strong>
  <%= @alias.payee %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @alias.memo %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= link_to @alias.vendor.name, vendor_path(@alias.vendor) %>
</p>

<%= link_to 'Edit', edit_alias_path(@alias) %> |
<%= link_to 'Back', aliases_path %>