config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :houses
  resources :performed_maintenances
  resources :performed_maintenance_parts
  resources :parts
  resources :services
  resources :maintenances
  resources :maintenance_schedules
  post 'maintenance_schedules/import' => 'maintenance_schedules#import', as: :import_maintenance_schedule
  resources :canonical_vehicles
  resources :steps
  resources :fillups
  resources :vehicles
  get 'vehicles/:id/image' => 'vehicles#image', as: :vehicle_image
  post 'vehicles/:id/fillup' => 'vehicles#fillup', as: :vehicle_fillup
  post 'vehicles/:id/import' => 'vehicles#import', as: :import_vehicle_fillups
  resources :aliases
  resources :transactions
  resources :vendors
  resources :accounts
  post 'accounts/:id/import' => 'accounts#import', as: :import_account_transactions
  resources :checking_accounts, controller: 'accounts', type: 'CheckingAccount'
  resources :stock_accounts, controller: 'accounts', type: 'StockAccount'
  get 'welcome/index'

  devise_for :users
  resources :users, :only => [:show]

  root 'welcome#index'

end

app/models/maintenance_schedule.rb
class MaintenanceSchedule < ActiveRecord::Base

   has_many :canonical_vehicles
   accepts_nested_attributes_for :canonical_vehicles
   
   has_many :maintenances
   accepts_nested_attributes_for :maintenances

   def self.import(file)
      ms = MaintenanceSchedule.new(JSON.parse(file.read))
      ms.save
   end

end

app/controllers/maintenance_schedules_controller.rb
class MaintenanceSchedulesController < ApplicationController
  power :crud => :maintenance_schedules
  before_action :set_maintenance_schedule, only: [:show, :edit, :update, :destroy]

  # GET /maintenance_schedules
  # GET /maintenance_schedules.json
  def index
    @maintenance_schedules = current_power.maintenance_schedules
  end

  # GET /maintenance_schedules/1
  # GET /maintenance_schedules/1.json
  def show
  end

  # GET /maintenance_schedules/new
  def new
    @maintenance_schedule = MaintenanceSchedule.new
  end

  # GET /maintenance_schedules/1/edit
  def edit
  end

  # POST /maintenance_schedules/import
  def import
     redirect_to :back, notice: MaintenanceSchedule.import(params[:file])
  end

  # POST /maintenance_schedules
  # POST /maintenance_schedules.json
  def create
    @maintenance_schedule = MaintenanceSchedule.new(maintenance_schedule_params)

    respond_to do |format|
      if @maintenance_schedule.save
        format.html { redirect_to @maintenance_schedule, notice: 'Maintenance schedule was successfully created.' }
        format.json { render :show, status: :created, location: @maintenance_schedule }
      else
        format.html { render :new }
        format.json { render json: @maintenance_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_schedules/1
  # PATCH/PUT /maintenance_schedules/1.json
  def update
    respond_to do |format|
      if @maintenance_schedule.update(maintenance_schedule_params)
        format.html { redirect_to @maintenance_schedule, notice: 'Maintenance schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @maintenance_schedule }
      else
        format.html { render :edit }
        format.json { render json: @maintenance_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_schedules/1
  # DELETE /maintenance_schedules/1.json
  def destroy
    @maintenance_schedule.destroy
    respond_to do |format|
      format.html { redirect_to maintenance_schedules_url, notice: 'Maintenance schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_schedule
      @maintenance_schedule = current_power.maintenance_schedules.find_by(:id => params[:id])
      redirect_to maintenance_schedule_url unless @maintenance_schedule
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maintenance_schedule_params
      params.fetch(:maintenance_schedule, {})
    end
end

app/helpers/maintenance_schedules_helper.rb
module MaintenanceSchedulesHelper
end

app/views/maintenance_schedules/_form.html.erb
<%= form_for(@maintenance_schedule) do |f| %>
  <% if @maintenance_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maintenance_schedule.errors.count, "error") %> prohibited this maintenance_schedule from being saved:</h2>

      <ul>
      <% @maintenance_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maintenance_schedules/edit.html.erb
<h1>Editing Maintenance Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @maintenance_schedule %> |
<%= link_to 'Back', maintenance_schedules_path %>

app/views/maintenance_schedules/index.html.erb
<h1>Listing Maintenance Schedules</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_schedules.each do |maintenance_schedule| %>
      <tr>
        <td><%= maintenance_schedule %></td>
        <td><%= link_to 'Show', maintenance_schedule %></td>
        <% if current_power.updatable_maintenance_schedule?(maintenance_schedule) %>
        <td><%= link_to 'Edit', edit_maintenance_schedule_path(maintenance_schedule) %></td>
        <% end %>
        <% if current_power.destroyable_maintenance_schedule?(maintenance_schedule) %>
        <td><%= link_to 'Destroy', maintenance_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag import_maintenance_schedule_path, multipart: true, class: 'form-inline' do %>
   <%= file_field_tag :file, class: 'form-control' %>
   <%= submit_tag "Import", class: 'btn btn-submit' %>
<% end %>

<br>

<%= link_to 'New Maintenance schedule', new_maintenance_schedule_path %>

app/views/maintenance_schedules/new.html.erb
<h1>New Maintenance Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', maintenance_schedules_path %>

app/views/maintenance_schedules/show.html.erb
<h1>Canonical Vehicles</h1>
<ul>
<% @maintenance_schedule.canonical_vehicles.each do |vehicle| %>
<li><%= link_to vehicle, canonical_vehicle_path(vehicle) %></li>
<% end %>
</ul>
<h1>Maintenance Procedures</h1>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Item</th>
      <th colspan=2 style="text-align:center">Inspect</th>
      <th colspan=2 style="text-align:center">Replace</th>
      <th>Page</th>
      <th>PDF</th>
    </tr>
  </thead>
  <tbody>
    <% @maintenance_schedule.maintenances.each do |maintenance| %>
    <tr>
      <td><%= link_to maintenance.item, maintenance_path(maintenance) %></td>
      <td><% if maintenance.inspectMonths %><%= maintenance.inspectMonths %> months<% end %></td>
      <td><% if maintenance.inspectMiles %><%= maintenance.inspectMiles %> miles<% end %></td>
      <td><% if maintenance.replaceMonths %><%= maintenance.replaceMonths %> months<% end %></td>
      <td><% if maintenance.replaceMiles%><%= maintenance.replaceMiles %> miles<% end %></td>
      <td><%= maintenance.page %></td>
      <td><%= maintenance.pdf %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_power.updatable_maintenance_schedule?(@maintenance_schedule) %>
<%= link_to 'Edit', edit_maintenance_schedule_path(@maintenance_schedule) %> |
<% end %>
<%= link_to 'Back', maintenance_schedules_path %>