config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :houses
  resources :performed_maintenances
  resources :performed_maintenance_parts
  resources :parts
  resources :services
  resources :maintenances
  resources :maintenance_schedules
  post 'maintenance_schedules/import' => 'maintenance_schedules#import', as: :import_maintenance_schedule
  resources :canonical_vehicles
  resources :steps
  resources :fillups
  resources :vehicles
  get 'vehicles/:id/image' => 'vehicles#image', as: :vehicle_image
  post 'vehicles/:id/fillup' => 'vehicles#fillup', as: :vehicle_fillup
  post 'vehicles/:id/import' => 'vehicles#import', as: :import_vehicle_fillups
  resources :aliases
  resources :transactions
  resources :vendors
  resources :accounts
  post 'accounts/:id/import' => 'accounts#import', as: :import_account_transactions
  resources :checking_accounts, controller: 'accounts', type: 'CheckingAccount'
  resources :stock_accounts, controller: 'accounts', type: 'StockAccount'
  get 'welcome/index'

  devise_for :users
  resources :users, :only => [:show]

  root 'welcome#index'

end

app/models/fillup.rb
class Fillup < ActiveRecord::Base
   belongs_to :vehicle, inverse_of: :fillups
end

app/controllers/fillups_controller.rb
class FillupsController < ApplicationController
  power :fillups
  before_action :set_fillup, only: [:show, :edit, :update, :destroy]

  # GET /fillups
  # GET /fillups.json
  def index
    @fillups = current_power.fillups
  end

  # GET /fillups/1
  # GET /fillups/1.json
  def show
  end

  # GET /fillups/new
  def new
    @fillup = Fillup.new
  end

  # GET /fillups/1/edit
  def edit
  end

  # POST /fillups
  # POST /fillups.json
  def create
    @fillup = Fillup.new(fillup_params)

    respond_to do |format|
      if @fillup.save
        format.html { redirect_to @fillup, notice: 'Fillup was successfully created.' }
        format.json { render :show, status: :created, location: @fillup }
      else
        format.html { render :new }
        format.json { render json: @fillup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillups/1
  # PATCH/PUT /fillups/1.json
  def update
    respond_to do |format|
      if @fillup.update(fillup_params)
        format.html { redirect_to @fillup, notice: 'Fillup was successfully updated.' }
        format.json { render :show, status: :ok, location: @fillup }
      else
        format.html { render :edit }
        format.json { render json: @fillup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillups/1
  # DELETE /fillups/1.json
  def destroy
    @fillup.destroy
    respond_to do |format|
      format.html { redirect_to fillups_url, notice: 'Fillup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fillup
      @fillup = current_power.fillups.find_by(:id => params[:id])
      redirect_to fillups_url unless @fillup
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fillup_params
      params.require(:fillup).permit(:date, :odometer, :gallons, :ppg, :brand, :grade)
    end
end

app/helpers/fillups_helper.rb
module FillupsHelper
end

app/views/fillups/_form.html.erb
<%= form_for(@fillup) do |f| %>
  <% if @fillup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fillup.errors.count, "error") %> prohibited this fillup from being saved:</h2>

      <ul>
      <% @fillup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :odometer %><br>
    <%= f.number_field :odometer %>
  </div>
  <div class="field">
    <%= f.label :gallons %><br>
    <%= f.text_field :gallons %>
  </div>
  <div class="field">
    <%= f.label :ppg %><br>
    <%= f.text_field :ppg %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fillups/edit.html.erb
<h1>Editing Fillup</h1>

<%= render 'form' %>

<%= link_to 'Show', @fillup %> |
<%= link_to 'Back', fillups_path %>

app/views/fillups/index.html.erb
<h1>Listing Fillups</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Date</th>
      <th>Odometer</th>
      <th>Gallons</th>
      <th>Ppg</th>
      <th>Brand</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fillups.order(odometer: :desc).each do |fillup| %>
      <tr>
        <td><%= link_to fillup.vehicle, vehicle_path(fillup.vehicle) %></td>
        <td><%= fillup.date %></td>
        <td><%= fillup.odometer %></td>
        <td><%= fillup.gallons %></td>
        <td><%= fillup.ppg %></td>
        <td><%= fillup.brand %></td>
        <td><%= fillup.grade %></td>
        <td><%= link_to 'Show', fillup %></td>
        <td><%= link_to 'Edit', edit_fillup_path(fillup) %></td>
        <td><%= link_to 'Destroy', fillup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fillup', new_fillup_path %>

app/views/fillups/new.html.erb
<h1>New Fillup</h1>

<%= render 'form' %>

<%= link_to 'Back', fillups_path %>

app/views/fillups/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @fillup.date %>
</p>

<p>
  <strong>Odometer:</strong>
  <%= @fillup.odometer %>
</p>

<p>
  <strong>Gallons:</strong>
  <%= @fillup.gallons %>
</p>

<p>
  <strong>Ppg:</strong>
  <%= @fillup.ppg %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @fillup.brand %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @fillup.grade %>
</p>

<%= link_to 'Edit', edit_fillup_path(@fillup) %> |
<%= link_to 'Back', fillups_path %>