config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :houses
  resources :performed_maintenances
  resources :performed_maintenance_parts
  resources :parts
  resources :services
  resources :maintenances
  resources :maintenance_schedules
  post 'maintenance_schedules/import' => 'maintenance_schedules#import', as: :import_maintenance_schedule
  resources :canonical_vehicles
  resources :steps
  resources :fillups
  resources :vehicles
  get 'vehicles/:id/image' => 'vehicles#image', as: :vehicle_image
  post 'vehicles/:id/fillup' => 'vehicles#fillup', as: :vehicle_fillup
  post 'vehicles/:id/import' => 'vehicles#import', as: :import_vehicle_fillups
  resources :aliases
  resources :transactions
  resources :vendors
  resources :accounts
  post 'accounts/:id/import' => 'accounts#import', as: :import_account_transactions
  resources :checking_accounts, controller: 'accounts', type: 'CheckingAccount'
  resources :stock_accounts, controller: 'accounts', type: 'StockAccount'
  get 'welcome/index'

  devise_for :users
  resources :users, :only => [:show]

  root 'welcome#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user, inverse_of: :vehicles

  belongs_to :canonical_vehicle, inverse_of: :vehicles
  has_many :maintenances, through: :canonical_vehicle

  has_many :fillups

  has_many :services
  has_many :performed_maintenances, through: :services

  def to_s
    return self.canonical_vehicle.to_s
  end

  def current_odometer
    if self.fillups.first
      return self.fillups.order(date: :desc).first.odometer
    else
      return 0
    end
  end

  def image_file=(input_data)
    self.image = input_data.read
    self.content_type = input_data.content_type.chomp
  end

  def self.import(file, vehicle_id)
    mcount = 0
    count = 0

    if file.content_type == "application/json"
      json = JSON.parse(file.read)
      json["fillups_attributes"].each do |fillup_hash|
        fillup_hash["vehicle_id"] = vehicle_id
        if fillup = Fillup.where(odometer: fillup_hash["odometer"], vehicle_id: vehicle_id).first
          mcount += 1
        else
          fillup = Fillup.new(fillup_hash)
        end
        fillup.save
        count += 1
      end
      return "Imported " + (count - mcount).to_s + " new fillups from JSON and matched " + mcount.to_s + " existing fillups."
    elsif file.content_type == "text/csv"
      require 'date'
      File.foreach(file.path).with_index do |line, index|
        if(line.match("Date,Mileage,Action,Location,Cost,Gallons,PPG"))
          @type = "Mileage CSV"
          next
        elsif(line.match("Total:"))
          next
        elsif(@type.match("Mileage CSV"))
          array = line.split(',')
          array[2].sub!('Premium Fuel','91')
          array[2].sub!('Plus Fuel','89')
          array[2].sub!('Regular Fuel','86')
          @fillup = Fillup.where(
          date: Date.strptime(array[0], '%m/%d/%Y'),
          odometer: array[1],
          grade: array[2],
          brand: array[3],
          gallons: array[5],
          ppg: array[6]
          ).take || Fillup.new
          if(@fillup.odometer)
            mcount += 1
          else
            @fillup.vehicle_id = vehicle_id
            @fillup.date = Date.strptime(array[0], '%m/%d/%Y')
            @fillup.odometer = array[1]
            @fillup.grade = array[2]
            @fillup.brand = array[3]
            @fillup.gallons = array[5]
            @fillup.ppg = array[6]
            @fillup.save
          end
          count += 1
        end
      end
      return "Imported #{count} transactions from #{@type}. #{count - mcount} were new and #{mcount} matched existing transactions"
    end
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  power :vehicles
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy, :image, :fillup, :import]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = current_power.vehicles
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    #      @fillups = Kaminari.paginate_array(@vehicle.fillups.sort { |a,b| a.date <=> b.date }.reverse).page(params[:page]).per(10)
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /accounts/1/import
  def import
    redirect_to :back, notice: Vehicle.import(params[:file], @vehicle.id)
  end

  # GET /vehicles/1/image
  def image
    send_data(@vehicle.image, :type => @vehicle.content_type, :disposition => 'inline')
  end

  # POST /vehicles/1/fillup
  def fillup
    fillup = Fillup.new(fillup_params)
    fillup.vehicle = @vehicle
    fillup.save
    redirect_to vehicle_path(@vehicle)
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicles_path, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = current_power.vehicles.find_by(:id => params[:id])
    redirect_to vehicles_url unless @vehicle
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.require(:vehicle).permit(:vin, :user_id, :image_file, :canonical_vehicle_id)
  end

  def fillup_params
    params.require(:fillup).permit(:date, :odometer, :brand, :grade, :gallons, :ppg)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= f.select :canonical_vehicle_id, options_for_select(CanonicalVehicle.order(:year, :make, :model).map{|s|[s.year.to_s + ' ' + s.make + ' ' + s.model, s.id]}) %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.file_field :image_file %>
  </div>

  <br>
  <div class="actions">
     <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<div class="row">
   <% current_user.vehicles.sort {|a,b| a.updated_at <=> b.updated_at}.each do |vehicle| %>
      <div class="col-sm-4">
	 <div class="thumbnail">
	    <%= link_to image_tag(vehicle_image_path(vehicle)), vehicle %>
	    <div class="caption">
	       <%= vehicle.canonical_vehicle.year %> <%= vehicle.canonical_vehicle.make %> <%= vehicle.canonical_vehicle.model %><br>
	       [ <%= link_to 'Show', vehicle %> | <%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %> ]
	    </div>
	 </div>
      </div>
   <% end %>
</div>
<%= form_for(:vehicle, url: vehicles_path, html: { :class => "form-inline" }) do |f| %>
   <%= f.select :canonical_vehicle_id, options_for_select(CanonicalVehicle.order(:year, :make, :model).map{|s|[s, s.id]}) %>
   <%= f.text_field(:vin, { :class => 'form-control', :placeholder => 'vin' }) %>
   <%= f.submit("Add New", { :class => 'btn btn-default' }) %>
   <%= f.file_field(:image_file, { :style => 'padding-top:1em' }) %>
<% end %>

app/views/vehicles/new.html.erb
<div class="panel panel-primary">
   <div class="panel-heading">Add a Vehicle</div>
   <div class="panel-body">
      <%= form_for(:vehicle, url: '/vehicles', html: { :class => "form-inline" }) do |f| %>
	 <div class="form-group">
	    <%= f.select :canonical_vehicle_id, options_for_select(CanonicalVehicle.order(:year, :make, :model).map{|s|[s.year.to_s + ' ' + s.make + ' ' + s.model, s.id]}) %>
	    <%= f.text_field(:vin, { :class => 'form-control', :placeholder => 'vin' }) %>
	    <%= f.submit("Add Vehicle", { :class => 'btn btn-submit' }) %>
	 </div>
      <% end %>
   </div>
</div>

app/views/vehicles/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @vehicle.canonical_vehicle.year %> <%= @vehicle.canonical_vehicle.make %> <%= @vehicle.canonical_vehicle.model %> <% if @vehicle.vin != "" %> (<%= @vehicle.vin %>) <% end %>
    <%= link_to content_tag(:span, nil, { :class => 'glyphicon glyphicon-edit pull-right', :style => 'color:white' }), edit_vehicle_path(@vehicle) %>
  </div>
  <div class="panel-body">
    <h3>Upcoming Service</h3>
    <span class="label label-primaly"><%= @vehicle.current_odometer %></span>
    <table class="table table-striped" style="display:block; overflow:auto; max-height: 10em">
      <tbody>
        <% @vehicle.maintenances.sort { |a,b| a.miles_until_due(@vehicle) <=> b.miles_until_due(@vehicle) }.each do |maintenance| %>
        <tr>
          <td data-toggle="modal" data-target="#maintenance-<%= maintenance.id %>"><%= maintenance.item %></td>
          <td<% if maintenance.latest_performed_maintenance(@vehicle) %> data-toggle="modal" data-target="#service-<%= maintenance.latest_performed_maintenance(@vehicle).service.id %>"<% end %>>
            <% if maintenance.months_until_due(@vehicle).is_a? Integer %>
            <% if maintenance.months_until_due(@vehicle) <= 0 %>
            <span class="label label-danger">
              <%= -maintenance.months_until_due(@vehicle) %> months overdue
            <% else %>
            <span class="label label-success">
              <%= maintenance.months_until_due(@vehicle) %> months remaining
            <% end %>
            <% elsif maintenance.months_until_due(@vehicle).is_a? String %>
            <span class="label label-success"><%= maintenance.months_until_due(@vehicle) %></span>
            <% else %>
            <span class="label label-danger">Never Performed
            <% end %>
            </span>
          </td>
          <td<% if maintenance.latest_performed_maintenance(@vehicle) %> data-toggle="modal" data-target="#service-<%= maintenance.latest_performed_maintenance(@vehicle).service.id %>"<% end %>>
            <% if maintenance.miles_until_due(@vehicle) <= 0 %>
            <span class="label label-danger">
              <%= -maintenance.miles_until_due(@vehicle) %> miles overdue
            <% else %>
            <span class="label label-success">
              <%= maintenance.miles_until_due(@vehicle) %> miles remaining
            <% end %>
            </span>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Mileage History</h3>
    <table class="table table-striped" style="display:block; overflow:auto; max-height: 20em">
      <thead>
        <tr>
          <th>Date</th>
          <th>Odometer</th>
          <th>Brand</th>
          <th>Grade</th>
          <th>Gallon</th>
          <th>PPG</th>
          <th>Cost</th>
          <th>MPG</th>
        </tr>
      </thead>
      <tbody>
        <%= form_for(:fillup, url: vehicle_fillup_path) do |f| %>
        <tr>
          <td><%= f.date_select(:date, :class => 'form-control', :placeholder => 'date') %></td>
          <td><%= f.number_field(:odometer, :class => 'form-control', :placeholder => 'odometer') %></td>
          <td><%= f.text_field(:brand, :class => 'form-control', :placeholder => 'brand') %></td>
          <td><%= f.text_field(:grade, :class => 'form-control', :placeholder => 'grade') %></td>
          <td><%= f.number_field(:gallons, :class => 'form-control', :placeholder => 'gallons', :step => 0.001) %></td>
          <td><%= f.number_field(:ppg, :class => 'form-control', :placeholder => 'ppg', :step => 0.001) %></td>
          <td colspan=2><%= f.submit("Fillup", :class => 'btn btn-default') %></td>
        </tr>
        <% end %>
        <% @vehicle.fillups.sort { |a,b| a.date <=> b.date }.reverse.each do |fillup| %>
        <tr>
          <td><%= fillup.date %></td>
          <td><%= fillup.odometer %></td>
          <td><%= fillup.brand %></td>
          <td><%= fillup.grade %></td>
          <td><%= fillup.gallons %></td>
          <td>$<%= fillup.ppg %></td>
          <td>$<%= number_with_precision fillup.ppg * fillup.gallons, :precision => 2 %></td>
          <td>
            <% if @last %>
            <%= number_with_precision (@last.odometer - fillup.odometer) / @last.gallons, :precision => 0 %>
            <% end %>
          </td>
        </tr>
        <% @last = fillup %>
        <% end %>
      </tbody>
    </table>
    <h3>Service History</h3>
    <table class="table table-striped table-hover" style="display:block; overflow:auto; max-height: 20em">
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Odometer</th>
        </tr>
      </thead>
      <tbody>
        <% @vehicle.services.sort { |a,b| a.date <=> b.date }.reverse.each do |service| %>
        <tr data-toggle="modal" data-target="#service-<%= service.id %>">
          <td><%= service.date %></td>
          <td><%= service.location %></td>
          <td><%= service.odometer %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <% @vehicle.maintenances.each do |maintenance| %>
    <div class="modal fade" id="maintenance-<%= maintenance.id %>">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="modal-title"><%= maintenance.item %></h3>
          </div>
          <div class="modal-body">
            <%= render partial: "maintenances/table", locals: {maintenance: maintenance} %>
            <%= render partial: "maintenances/steps", locals: {maintenance: maintenance} %>
          </div>
          <div class="modal-footer">
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <% end %>

    <% @vehicle.services.each do |service| %>
    <div class="modal fade" id="service-<%= service.id %>">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="modal-title"><%= service.location %></h3>
          </div>
          <div class="modal-body">
            <%= render partial: "services/table", locals: {service: service} %>
          </div>
          <div class="modal-footer">
            <span class="label label-primary"><%= service.odometer %></span></h3>
            <span class="label label-primary"><%= service.date %></span></h3>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <% end %>
  </div>

  <br>
  <div class="panel-footer">
    <%= form_tag import_vehicle_fillups_path, multipart: true, class: 'form-inline pull-right' do %>
    <%= file_field_tag :file, class: 'form-control' %>
    <%= submit_tag "Import", class: 'btn btn-submit' %>
    <% end %>
    <%= link_to content_tag(:span, nil, :class => 'glyphicon glyphicon-download-alt', :title => 'Download (JSON)'), vehicle_path(:format => 'json') %>
  </div>
</div>